/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[42];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define E parms[0] 
 #define delta0 parms[1] 
 #define a0 parms[2] 
 #define eta parms[3] 
 #define c parms[4] 
 #define kappa parms[5] 
 #define y0_0 parms[6] 
 #define y1_0 parms[7] 
 #define y2_0 parms[8] 
 #define y3_0 parms[9] 
 #define y4_0 parms[10] 
 #define y5_0 parms[11] 
 #define y6_0 parms[12] 
 #define y7_0 parms[13] 
 #define y8_0 parms[14] 
 #define y9_0 parms[15] 
 #define y10_0 parms[16] 
 #define y11_0 parms[17] 
 #define y12_0 parms[18] 
 #define y13_0 parms[19] 
 #define y14_0 parms[20] 
 #define y15_0 parms[21] 
 #define y16_0 parms[22] 
 #define y17_0 parms[23] 
 #define y18_0 parms[24] 
 #define y19_0 parms[25] 
 #define y20_0 parms[26] 
 #define y21_0 parms[27] 
 #define y22_0 parms[28] 
 #define y23_0 parms[29] 
 #define y24_0 parms[30] 
 #define y25_0 parms[31] 
 #define y26_0 parms[32] 
 #define y27_0 parms[33] 
 #define y28_0 parms[34] 
 #define y29_0 parms[35] 
 #define y30_0 parms[36] 
 #define y31_0 parms[37] 
 #define y32_0 parms[38] 
 #define y33_0 parms[39] 
 #define y34_0 parms[40] 
 #define y35_0 parms[41] 
#define tmin range[0]
#define tmax range[1]


void spring2D_mixedBC_initmod(void (* odeparms)(int *, double *)) {
	 int N=42;
	 odeparms(&N, parms);
}

void spring2D_mixedBC_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void spring2D_mixedBC_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = y[1];
 	 ydot[1] = (E/(delta0*pow(a0,2.0)))*(y[6]+0.0+y[2]+y[0]-4.0*y[0])+(1.0/(delta0*a0))*(((eta*(1.0+(y[6]-y[0])/a0))-(eta*(1.0+(y[0]-0.0)/a0)))+((eta*(1.0+(y[2]-y[0])/a0))-(0.0)))-(c/delta0)*y[1]-(kappa/delta0)*y[0];
 	 ydot[2] = y[3];
 	 ydot[3] = (E/(delta0*pow(a0,2.0)))*(y[8]+0.0+y[4]+y[0]-4.0*y[2])+(1.0/(delta0*a0))*(((eta*(1.0+(y[8]-y[2])/a0))-(eta*(1.0+(y[2]-0.0)/a0)))+((eta*(1.0+(y[4]-y[2])/a0))-(eta*(1.0+(y[2]-y[0])/a0))))-(c/delta0)*y[3]-(kappa/delta0)*y[2];
 	 ydot[4] = y[5];
 	 ydot[5] = (E/(delta0*pow(a0,2.0)))*(y[10]+0.0+y[4]+y[2]-4.0*y[4])+(1.0/(delta0*a0))*(((eta*(1.0+(y[10]-y[4])/a0))-(eta*(1.0+(y[4]-0.0)/a0)))+((0.0)-(eta*(1.0+(y[4]-y[2])/a0))))-(c/delta0)*y[5]-(kappa/delta0)*y[4];
 	 ydot[6] = y[7];
 	 ydot[7] = (E/(delta0*pow(a0,2.0)))*(y[12]+y[0]+y[8]+y[6]-4.0*y[6])+(1.0/(delta0*a0))*(((eta*(1.0+(y[12]-y[6])/a0))-(eta*(1.0+(y[6]-y[0])/a0)))+((eta*(1.0+(y[8]-y[6])/a0))-(0.0)))-(c/delta0)*y[7]-(kappa/delta0)*y[6];
 	 ydot[8] = y[9];
 	 ydot[9] = (E/(delta0*pow(a0,2.0)))*(y[14]+y[2]+y[10]+y[6]-4.0*y[8])+(1.0/(delta0*a0))*(((eta*(1.0+(y[14]-y[8])/a0))-(eta*(1.0+(y[8]-y[2])/a0)))+((eta*(1.0+(y[10]-y[8])/a0))-(eta*(1.0+(y[8]-y[6])/a0))))-(c/delta0)*y[9]-(kappa/delta0)*y[8];
 	 ydot[10] = y[11];
 	 ydot[11] = (E/(delta0*pow(a0,2.0)))*(y[16]+y[4]+y[10]+y[8]-4.0*y[10])+(1.0/(delta0*a0))*(((eta*(1.0+(y[16]-y[10])/a0))-(eta*(1.0+(y[10]-y[4])/a0)))+((0.0)-(eta*(1.0+(y[10]-y[8])/a0))))-(c/delta0)*y[11]-(kappa/delta0)*y[10];
 	 ydot[12] = y[13];
 	 ydot[13] = (E/(delta0*pow(a0,2.0)))*(y[18]+y[6]+y[14]+y[12]-4.0*y[12])+(1.0/(delta0*a0))*(((eta*(1.0+(y[18]-y[12])/a0))-(eta*(1.0+(y[12]-y[6])/a0)))+((eta*(1.0+(y[14]-y[12])/a0))-(0.0)))-(c/delta0)*y[13]-(kappa/delta0)*y[12];
 	 ydot[14] = y[15];
 	 ydot[15] = (E/(delta0*pow(a0,2.0)))*(y[20]+y[8]+y[16]+y[12]-4.0*y[14])+(1.0/(delta0*a0))*(((eta*(1.0+(y[20]-y[14])/a0))-(eta*(1.0+(y[14]-y[8])/a0)))+((eta*(1.0+(y[16]-y[14])/a0))-(eta*(1.0+(y[14]-y[12])/a0))))-(c/delta0)*y[15]-(kappa/delta0)*y[14];
 	 ydot[16] = y[17];
 	 ydot[17] = (E/(delta0*pow(a0,2.0)))*(y[22]+y[10]+y[16]+y[14]-4.0*y[16])+(1.0/(delta0*a0))*(((eta*(1.0+(y[22]-y[16])/a0))-(eta*(1.0+(y[16]-y[10])/a0)))+((0.0)-(eta*(1.0+(y[16]-y[14])/a0))))-(c/delta0)*y[17]-(kappa/delta0)*y[16];
 	 ydot[18] = y[19];
 	 ydot[19] = (E/(delta0*pow(a0,2.0)))*(y[24]+y[12]+y[20]+y[18]-4.0*y[18])+(1.0/(delta0*a0))*(((eta*(1.0+(y[24]-y[18])/a0))-(eta*(1.0+(y[18]-y[12])/a0)))+((eta*(1.0+(y[20]-y[18])/a0))-(0.0)))-(c/delta0)*y[19]-(kappa/delta0)*y[18];
 	 ydot[20] = y[21];
 	 ydot[21] = (E/(delta0*pow(a0,2.0)))*(y[26]+y[14]+y[22]+y[18]-4.0*y[20])+(1.0/(delta0*a0))*(((eta*(1.0+(y[26]-y[20])/a0))-(eta*(1.0+(y[20]-y[14])/a0)))+((eta*(1.0+(y[22]-y[20])/a0))-(eta*(1.0+(y[20]-y[18])/a0))))-(c/delta0)*y[21]-(kappa/delta0)*y[20];
 	 ydot[22] = y[23];
 	 ydot[23] = (E/(delta0*pow(a0,2.0)))*(y[28]+y[16]+y[22]+y[20]-4.0*y[22])+(1.0/(delta0*a0))*(((eta*(1.0+(y[28]-y[22])/a0))-(eta*(1.0+(y[22]-y[16])/a0)))+((0.0)-(eta*(1.0+(y[22]-y[20])/a0))))-(c/delta0)*y[23]-(kappa/delta0)*y[22];
 	 ydot[24] = y[25];
 	 ydot[25] = (E/(delta0*pow(a0,2.0)))*(y[30]+y[18]+y[26]+y[24]-4.0*y[24])+(1.0/(delta0*a0))*(((eta*(1.0+(y[30]-y[24])/a0))-(eta*(1.0+(y[24]-y[18])/a0)))+((eta*(1.0+(y[26]-y[24])/a0))-(0.0)))-(c/delta0)*y[25]-(kappa/delta0)*y[24];
 	 ydot[26] = y[27];
 	 ydot[27] = (E/(delta0*pow(a0,2.0)))*(y[32]+y[20]+y[28]+y[24]-4.0*y[26])+(1.0/(delta0*a0))*(((eta*(1.0+(y[32]-y[26])/a0))-(eta*(1.0+(y[26]-y[20])/a0)))+((eta*(1.0+(y[28]-y[26])/a0))-(eta*(1.0+(y[26]-y[24])/a0))))-(c/delta0)*y[27]-(kappa/delta0)*y[26];
 	 ydot[28] = y[29];
 	 ydot[29] = (E/(delta0*pow(a0,2.0)))*(y[34]+y[22]+y[28]+y[26]-4.0*y[28])+(1.0/(delta0*a0))*(((eta*(1.0+(y[34]-y[28])/a0))-(eta*(1.0+(y[28]-y[22])/a0)))+((0.0)-(eta*(1.0+(y[28]-y[26])/a0))))-(c/delta0)*y[29]-(kappa/delta0)*y[28];
 	 ydot[30] = y[31];
 	 ydot[31] = (E/(delta0*pow(a0,2.0)))*(y[30]+y[24]+y[32]+y[30]-4.0*y[30])+(1.0/(delta0*a0))*(((0.0)-(eta*(1.0+(y[30]-y[24])/a0)))+((eta*(1.0+(y[32]-y[30])/a0))-(0.0)))-(c/delta0)*y[31]-(kappa/delta0)*y[30];
 	 ydot[32] = y[33];
 	 ydot[33] = (E/(delta0*pow(a0,2.0)))*(y[32]+y[26]+y[34]+y[30]-4.0*y[32])+(1.0/(delta0*a0))*(((0.0)-(eta*(1.0+(y[32]-y[26])/a0)))+((eta*(1.0+(y[34]-y[32])/a0))-(eta*(1.0+(y[32]-y[30])/a0))))-(c/delta0)*y[33]-(kappa/delta0)*y[32];
 	 ydot[34] = y[35];
 	 ydot[35] = (E/(delta0*pow(a0,2.0)))*(y[34]+y[28]+y[34]+y[32]-4.0*y[34])+(1.0/(delta0*a0))*(((0.0)-(eta*(1.0+(y[34]-y[28])/a0)))+((0.0)-(eta*(1.0+(y[34]-y[32])/a0))))-(c/delta0)*y[35]-(kappa/delta0)*y[34];

}

